// Seed 100 Dubai Mall retailers ranked by combined online+offline footfall (Fortune 100 style)
const mysql = require('mysql2/promise');
const fs    = require('fs');

const env = fs.readFileSync('.env', 'utf8').split('\n').reduce((a, l) => {
  const [k, ...v] = l.split('=');
  if (k && !l.startsWith('#')) a[k.trim()] = v.join('=').trim().replace(/^"|"$/g, '');
  return a;
}, {});

// fortune_rank | name | category | category_slug | description | website_url
// offline_rank | online_rank | annual_footfall_m | offline_revenue_m | online_revenue_m | yoy_growth | floor_level | is_featured | tier
// tier: 1=all(1-20), 2=premium(21-50), 3=admin(51-100)
const BRANDS = [
  // ── TIER 1: Visible to all users (Rank 1-20) ─────────────────────────────
  [1,  'Apple Store',         'Electronics',     'electronics',  'World\'s highest-revenue Apple retail location per sq ft — Dubai Mall draws 6.2M Apple visitors annually.',         'https://www.apple.com/ae/retail/thedubaimall/',  1,  3,  6.2, 820.0, 540.0,  12.4, 'GF – South',         1, 1],
  [2,  'LEGO Store',          'Toys & Family',   'toys',         'Largest LEGO store in the MENA region — 4,800 sq ft of interactive brick building and exclusive sets.',            'https://www.lego.com/en-ae',                     2,  8,  5.1, 280.0,  95.0,  18.2, 'LG – Family Zone',   1, 1],
  [3,  'H&M',                 'Fashion',         'fashion',      'Dubai Mall flagship — H&M\'s highest-grossing Middle East outlet with 3 floors of trend-forward collections.',     'https://www2.hm.com/en_ae/',                     3,  2,  4.9, 310.0, 180.0,   9.1, '1F – Fashion Ave',   1, 1],
  [4,  'Zara',                'Fashion',         'fashion',      'Flagship Zara with 24,000 sq ft — one of Inditex\'s top 5 performing global stores by annual revenue.',            'https://www.zara.com/ae/',                       4,  1,  4.7, 390.0, 210.0,  11.5, '1F – Fashion Ave',   1, 1],
  [5,  'Sephora',             'Beauty',          'beauty',       'MENA\'s beauty capital — 14,000 products across 300 brands. In-store Beauty Workshops fill weeks in advance.',     'https://www.sephora.ae/',                        5,  4,  4.3, 260.0, 190.0,  15.8, 'GF – Beauty Hall',   1, 1],
  [6,  'Nike',                'Sports',          'sports',       'Nike\'s largest Middle East store — 3 floors including the exclusive Nike By You customisation studio.',            'https://www.nike.com/ae',                        6,  5,  4.0, 295.0, 160.0,  13.2, '1F – Sports Zone',   1, 1],
  [7,  'Adidas',              'Sports',          'sports',       'Two-floor Adidas flagship with the region\'s only Adidas Running Lab — real-time gait analysis included.',         'https://www.adidas.ae/',                         7,  6,  3.8, 240.0, 145.0,  10.9, '1F – Sports Zone',   1, 1],
  [8,  'Hamleys',             'Toys & Family',   'toys',         '25,000 sq ft of pure childhood wonder — the UK\'s iconic toy emporium at its most spectacular global address.',   'https://hamleys.com/stores/dubai-mall',          8, 12,  3.6, 195.0,  60.0,  14.3, 'LG – Family Zone',   1, 1],
  [9,  'Bath & Body Works',   'Beauty',          'beauty',       'America\'s beloved fragrance house — Dubai Mall location ranks #1 globally by units sold per sq ft.',             'https://www.bathandbodyworks.com.sa/',           9,  7,  3.4, 185.0, 110.0,  16.7, 'GF – Beauty Hall',   1, 1],
  [10, 'Forever 21',          'Fashion',         'fashion',      'Three-storey trend destination drawing the highest Gen-Z footfall in any UAE retail location.',                  'https://www.forever21.ae/',                     10, 11,  3.2, 170.0,  80.0,   7.2, '1F – Fashion Ave',   1, 1],
  [11, 'Kinokuniya',          'Books & Culture', 'books',        'Asia\'s premier bookstore — 120,000+ titles in 8 languages. A sanctuary of intellect inside the world\'s busiest mall.', 'https://ae.kinokuniya.com/',             11, 18,  3.0, 140.0,  45.0,   8.5, '2F – Culture Wing',  1, 1],
  [12, 'Uniqlo',              'Fashion',         'fashion',      'Tokyo precision meets Dubai luxury — LifeWear philosophy draws minimalists and fashionistas in equal measure.',     'https://www.uniqlo.com/ae/',                    12,  9,  2.9, 165.0, 120.0,  19.4, '1F – Fashion Ave',   1, 1],
  [13, 'Marks & Spencer',     'Fashion & Food',  'fashion',      'British institution with Dubai\'s finest M&S Food Hall — weekend picnic baskets sold out before 11am.',           'https://www.marksandspencer.com/ae/',           13, 14,  2.8, 210.0,  75.0,   6.8, 'GF – Main Entrance', 1, 1],
  [14, 'Pull & Bear',         'Fashion',         'fashion',      'Inditex\'s street-culture powerhouse — skateboard culture and music aesthetics define Dubai\'s youth scene here.', 'https://www.pullandbear.com/ae/',              14, 10,  2.7, 155.0,  95.0,   9.3, '1F – Fashion Ave',   1, 1],
  [15, 'Massimo Dutti',       'Fashion',         'fashion',      'Sophisticated European refinement — the go-to destination for Dubai\'s professional elite and business travellers.','https://www.massimodutti.com/ae/',            15, 16,  2.6, 180.0,  85.0,   8.1, '1F – Fashion Ave',   1, 1],
  [16, 'Bershka',             'Fashion',         'fashion',      'Bold, colourful, rebellious — Bershka captures Dubai\'s Gen-Z energy with the Gulf\'s largest streetwear floor.', 'https://www.bershka.com/ae/',                  16, 13,  2.5, 148.0,  78.0,  10.2, '1F – Fashion Ave',   1, 1],
  [17, 'Samsung Experience',  'Electronics',     'electronics',  'Cutting-edge Samsung showroom — Galaxy AI, foldables, and the world\'s largest curved QLED display wall.',        'https://www.samsung.com/ae/experience-store/', 17, 15,  2.4, 200.0, 130.0,  14.5, 'GF – South',          1, 1],
  [18, 'Stradivarius',        'Fashion',         'fashion',      'Feminine romance meets urban edge — Stradivarius Dubai Mall leads Gulf sales for the Inditex group.',              'https://www.stradivarius.com/ae/',              18, 17,  2.3, 135.0,  70.0,   7.6, '1F – Fashion Ave',   1, 1],
  [19, 'GAP',                 'Fashion',         'fashion',      'American heritage denim and casual — Dubai Mall GAP is the brand\'s highest-revenue store in the MENA region.',   'https://www.gap.com/ae/',                       19, 19,  2.2, 125.0,  65.0,   5.9, '1F – Fashion Ave',   1, 1],
  [20, 'Pandora',             'Jewellery',       'jewellery',    'The world\'s most gifted jewellery brand — 1,200+ charm combinations. Queue forms at opening on Valentine\'s Day.','https://www.pandora.net/ae/',                  20, 20,  2.1, 160.0, 140.0,  13.1, 'GF – Jewellery Row',  1, 1],

  // ── TIER 2: Premium users (Rank 21-50) ────────────────────────────────────
  [21, 'CHANEL',              'Luxury',          'luxury',       'The apex of French haute couture — Chanel Dubai Mall is among top 3 globally by revenue per visitor.',            'https://www.chanel.com/ae/',                    21, 22,  1.9, 980.0, 520.0,  11.3, '2F – Fashion Ave',   1, 2],
  [22, 'Louis Vuitton',       'Luxury',          'luxury',       'The world\'s most recognisable luxury monogram — LV Dubai Mall spans 3 floors and a private VIP penthouse suite.','https://ae.louisvuitton.com/',                 22, 21,  1.8,1100.0, 480.0,   9.8, '2F – Fashion Ave',   1, 2],
  [23, 'Gucci',               'Luxury',          'luxury',       'Italian opulence redefined for the Gulf — Gucci\'s Dubai flagship draws royalty, celebrities, and connoisseurs.',  'https://www.gucci.com/ae/',                    23, 25,  1.7, 850.0, 390.0,  12.1, '2F – Fashion Ave',   1, 2],
  [24, 'Dior',                'Luxury',          'luxury',       'Parisian grandeur translated into 14,000 sq ft of immersive luxury — the entire SS collection on opening day.',   'https://www.dior.com/en_ae',                   24, 23,  1.6, 790.0, 360.0,  10.4, '2F – Fashion Ave',   1, 2],
  [25, 'Prada',               'Luxury',          'luxury',       'Milan\'s most cerebral fashion house — Prada Dubai is the largest Prada boutique in the entire Middle East.',      'https://www.prada.com/ae/',                    25, 27,  1.5, 720.0, 310.0,   8.9, '2F – Fashion Ave',   1, 2],
  [26, 'Hermès',              'Luxury',          'luxury',       'The Birkin waiting list begins here — Hermès Dubai Mall receives the world\'s most allocated product drops.',      'https://www.hermes.com/ae/',                   26, 30,  1.4, 940.0, 280.0,   7.5, '2F – Fashion Ave',   1, 2],
  [27, 'Burberry',            'Luxury',          'luxury',       'British sartorial heritage — Burberry\'s trench coats, check scarves, and digital art installations all in one.',  'https://ae.burberry.com/',                     27, 26,  1.3, 560.0, 300.0,   9.2, '2F – Fashion Ave',   1, 2],
  [28, 'Valentino',           'Luxury',          'luxury',       'Roman romanticism at its most exquisite — Valentino Dubai is the brand\'s most-visited boutique globally.',        'https://www.valentino.com/ae/',                28, 28,  1.2, 620.0, 270.0,  10.8, '2F – Fashion Ave',   1, 2],
  [29, 'Versace',             'Luxury',          'luxury',       'Medusa presides over Dubai\'s boldest luxury address — gold, baroque, and unapologetically opulent.',              'https://www.versace.com/ae/',                  29, 24,  1.2, 580.0, 310.0,  11.5, '2F – Fashion Ave',   1, 2],
  [30, 'Tiffany & Co.',       'Jewellery',       'jewellery',    'Breakfast at Tiffany\'s — Dubai edition. The blue box is the most photographed retail package in the Gulf.',       'https://www.tiffany.ae/',                      30, 29,  1.1, 650.0, 380.0,  14.2, '2F – Jewellery Row',  1, 2],
  [31, 'Cartier',             'Jewellery',       'jewellery',    'The jeweller of kings — Cartier Dubai Mall hosts 400+ exclusive timepieces and the Love collection centrepiece.',  'https://www.cartier.ae/',                      31, 32,  1.1, 820.0, 340.0,  12.6, '2F – Jewellery Row',  1, 2],
  [32, 'Rolex',               'Watches',         'watches',      'The crown of horology — a Rolex Daytona exits this boutique every 47 minutes. Waitlists span 24 months.',         'https://www.rolex.com/',                       32, 35,  1.0, 980.0, 180.0,   8.4, '2F – Watch Gallery', 1, 2],
  [33, 'Swarovski',           'Jewellery',       'jewellery',    'Crystal empire — Swarovski Dubai Mall showcases 6,000 individual crystal pieces in its signature light cave.',     'https://www.swarovski.com/ae/',                33, 31,  1.0, 190.0, 140.0,  10.1, 'GF – Crystal Walk',  1, 2],
  [34, 'MAC Cosmetics',       'Beauty',          'beauty',       'Professional makeup for everyone — MAC Dubai Mall is the brand\'s busiest counter globally. 1,500+ shades.',       'https://www.maccosmetics.ae/',                 34, 33,  0.9, 145.0, 130.0,  16.3, 'GF – Beauty Hall',   1, 2],
  [35, 'Jo Malone London',    'Fragrance',       'fragrance',    'The art of scent combination — Jo Malone Dubai serves private fragrance consultations 18 hours a day.',            'https://www.jomalone.ae/',                     35, 34,  0.9, 280.0, 195.0,  18.9, 'GF – Fragrance Hall', 1, 2],
  [36, 'Tom Ford',            'Luxury Fashion',  'luxury',       'Seduction in a store — Tom Ford Dubai Mall carries the full cosmetics, fragrance, and RTW collection.',            'https://www.tomford.ae/',                      36, 36,  0.8, 420.0, 250.0,  13.7, '2F – Fashion Ave',   1, 2],
  [37, 'Ralph Lauren',        'Fashion',         'fashion',      'American dream embodied — the Polo flagship serves Dubai\'s elite with full Purple Label and bespoke tailoring.',  'https://www.ralphlauren.ae/',                  37, 37,  0.8, 310.0, 175.0,   8.6, '1F – Fashion Ave',   1, 2],
  [38, 'Tommy Hilfiger',      'Fashion',         'fashion',      'Classic Americana reinvented — Tommy\'s Dubai Mall flagship is the region\'s most visited denim destination.',      'https://usa.tommy.com/en/',                    38, 38,  0.8, 280.0, 160.0,   9.4, '1F – Fashion Ave',   1, 2],
  [39, 'Calvin Klein',        'Fashion',         'fashion',      'Minimalist American luxury — CK Dubai Mall leads underwear and denim sales for the entire GCC region.',            'https://www.calvinklein.com/en-ae/',           39, 39,  0.7, 260.0, 150.0,   8.1, '1F – Fashion Ave',   1, 2],
  [40, 'Hugo Boss',           'Fashion',         'fashion',      'German precision tailoring — Boss Dubai Mall is the brand\'s largest global flagship by floor area.',              'https://www.hugoboss.com/ae/',                 40, 40,  0.7, 320.0, 155.0,   9.7, '1F – Fashion Ave',   1, 2],
  [41, 'Michael Kors',        'Accessories',     'accessories',  'The king of accessible luxury — MK Dubai Mall moves 400+ handbags daily during peak tourist season.',              'https://www.michaelkors.ae/',                  41, 41,  0.7, 230.0, 175.0,  11.2, '1F – Accessories',   1, 2],
  [42, 'Coach',               'Accessories',     'accessories',  'American leather craftsmanship — Coach Dubai Mall\'s leather customisation bar is booked 3 weeks ahead.',          'https://www.coach.ae/',                        42, 42,  0.6, 210.0, 145.0,  10.5, '1F – Accessories',   1, 2],
  [43, 'Armani',              'Luxury Fashion',  'luxury',       'Giorgio Armani\'s full universe under one roof — Emporio, EA7, Casa, and the exclusive Privé collection.',         'https://www.armani.com/ae/',                   43, 44,  0.6, 480.0, 210.0,   7.8, '2F – Fashion Ave',   1, 2],
  [44, 'Lacoste',             'Fashion',         'fashion',      'The legendary crocodile — Lacoste Dubai Mall\'s tennis heritage meets Gulf street culture in 12,000 sq ft.',       'https://www.lacoste.com/ae/',                  44, 43,  0.6, 195.0, 115.0,   8.3, '1F – Fashion Ave',   1, 2],
  [45, 'Dolce & Gabbana',     'Luxury Fashion',  'luxury',       'Sicilian passion exported to Downtown Dubai — D&G\'s bold prints and baroque jewellery dominate Fashion Ave.',     'https://www.dolcegabbana.com/ae/',             45, 46,  0.6, 510.0, 220.0,   9.1, '2F – Fashion Ave',   1, 2],
  [46, 'Fendi',               'Luxury',          'luxury',       'Roman luxury craft at its finest — Fendi Dubai Mall exclusively stocks the Baguette bag in 6 regional-only leathers.','https://www.fendi.com/ae/',                46, 47,  0.5, 680.0, 240.0,   8.7, '2F – Fashion Ave',   1, 2],
  [47, 'Kate Spade',          'Accessories',     'accessories',  'Playful sophistication — Kate Spade Dubai is consistently the brand\'s #1 global store by handbag velocity.',      'https://www.katespade.ae/',                    47, 45,  0.5, 195.0, 160.0,  12.4, '1F – Accessories',   1, 2],
  [48, 'Huawei Flagship',     'Electronics',     'electronics',  'Huawei\'s showcase beyond smartphones — foldables, smart watches, and MatePad Pro ecosystem all demonstrated live.','https://consumer.huawei.com/ae/',             48, 48,  0.5, 175.0, 210.0,  15.6, 'GF – Tech Hub',       1, 2],
  [49, 'Omega',               'Watches',         'watches',      'The watch that went to the Moon — Omega Dubai Mall keeps a Speedmaster signed by all 12 Apollo astronauts.',       'https://www.omegawatches.com/en-ae/',          49, 50,  0.5, 520.0, 155.0,   8.0, '2F – Watch Gallery', 1, 2],
  [50, 'Longchamp',           'Accessories',     'accessories',  'Paris distilled into canvas and leather — Longchamp\'s Dubai flagship is the brand\'s #2 global store.',           'https://ae.longchamp.com/',                    50, 49,  0.5, 185.0, 145.0,  10.3, '1F – Accessories',   1, 2],

  // ── TIER 3: Admin only (Rank 51-100) ──────────────────────────────────────
  [51, 'Bottega Veneta',      'Luxury',          'luxury',       'The quiet luxury anthem — Bottega\'s intrecciato weave defines understated power dressing for Dubai\'s elite.',    'https://www.bottegaveneta.com/ae/',            51, 55,  0.4, 640.0, 195.0,   7.2, '2F – Fashion Ave',   0, 3],
  [52, 'Balenciaga',          'Luxury Fashion',  'luxury',       'Vetements-era disruption meets Dubai excess — limited-edition drops sell out within minutes of Instagram posting.', 'https://www.balenciaga.com/ae/',              52, 52,  0.4, 590.0, 320.0,  16.8, '2F – Fashion Ave',   0, 3],
  [53, 'Saint Laurent',       'Luxury Fashion',  'luxury',       'Paris by night personified — YSL Dubai Mall hosts exclusive Le Smoking tuxedo consultations for the city\'s elite.','https://www.ysl.com/ae/',                    53, 54,  0.4, 570.0, 260.0,  11.4, '2F – Fashion Ave',   0, 3],
  [54, 'Givenchy',            'Luxury',          'luxury',       'Audrey Hepburn\'s couturier — Givenchy Dubai Mall exclusively carries the Shark Lock boot in regional colorways.',  'https://www.givenchy.com/en/',               54, 56,  0.4, 490.0, 210.0,   9.6, '2F – Fashion Ave',   0, 3],
  [55, 'Celine',              'Luxury',          'luxury',       'Hedi Slimane\'s precision — Celine Dubai Mall books out private styling consultations 6 weeks in advance.',         'https://www.celine.com/en-ae/',              55, 58,  0.3, 520.0, 195.0,   8.4, '2F – Fashion Ave',   0, 3],
  [56, 'Loewe',               'Luxury',          'luxury',       'Spain\'s finest luxury craft house — Loewe Puzzle bags at Dubai Mall carry a 14-month waiting list.',              'https://www.loewe.com/ae/',                  56, 60,  0.3, 480.0, 170.0,  12.1, '2F – Fashion Ave',   0, 3],
  [57, 'Alexander McQueen',   'Luxury Fashion',  'luxury',       'Dark romanticism for Dubai\'s avant-garde — McQueen Skull scarves remain the single most gifted item in store.',    'https://www.alexandermcqueen.com/ae/',       57, 57,  0.3, 440.0, 200.0,  10.3, '2F – Fashion Ave',   0, 3],
  [58, 'Miu Miu',             'Luxury',          'luxury',       'Prada\'s experimental younger sibling — Miu Miu Dubai leads global sales of the upcycled denim collection.',       'https://www.miumiu.com/ae/',                 58, 59,  0.3, 420.0, 215.0,  14.7, '2F – Fashion Ave',   0, 3],
  [59, 'Balmain',             'Luxury Fashion',  'luxury',       'Military precision meets Parisian glamour — Balmain Dubai outfits the most-followed fashion accounts in the Gulf.',  'https://www.balmain.com/ae/',               59, 53,  0.3, 460.0, 280.0,  13.2, '2F – Fashion Ave',   0, 3],
  [60, 'Patek Philippe',      'Watches',         'watches',      'The grandfather clock of horology — a Patek Philippe Nautilus at Dubai Mall appreciates 40% before leaving the store.','https://www.patek.com/en/',              60, 65,  0.3,1200.0, 120.0,   6.1, '2F – Watch Gallery', 0, 3],
  [61, 'Audemars Piguet',     'Watches',         'watches',      'Royal Oak — the watch that changed everything. AP Dubai Mall allocates only 12 stainless Royal Oaks per month.',   'https://www.audemarspiguet.com/en/',         61, 66,  0.3,1150.0, 110.0,   7.4, '2F – Watch Gallery', 0, 3],
  [62, 'Richard Mille',       'Watches',         'watches',      'The billion-dollar wrist — Richard Mille tourbillons at Dubai Mall start at AED 380,000. 18 sold last month.',     'https://www.richardmille.com/',              62, 70,  0.2,1800.0,  80.0,   5.8, '2F – Watch Gallery', 0, 3],
  [63, 'Bulgari',             'Jewellery',       'jewellery',    'Roman extravagance in gold and diamonds — Bulgari Dubai Mall\'s Serpenti collection is the Gulf\'s top gifted jewel.','https://www.bulgari.com/en-ae/',           63, 62,  0.2, 880.0, 290.0,  10.5, '2F – Jewellery Row',  0, 3],
  [64, 'Van Cleef & Arpels',  'Jewellery',       'jewellery',    'The Alhambra\'s home — VCA Dubai Mall receives the most personalised engraving requests of any global boutique.',  'https://www.vancleefarpels.com/ae/',         64, 68,  0.2, 960.0, 210.0,   8.9, '2F – Jewellery Row',  0, 3],
  [65, 'Chopard',             'Watches & Jewels','watches',      'Geneva craftsmanship meets Gulf opulence — Chopard\'s Happy Diamonds collection inspired 3 regional exclusives.',   'https://www.chopard.com/en-ae/',             65, 67,  0.2, 720.0, 185.0,   9.3, '2F – Watch Gallery', 0, 3],
  [66, 'Harry Winston',       'Jewellery',       'jewellery',    'The King of Diamonds — Harry Winston Dubai Mall holds the Gulf\'s largest inventory of D-Flawless stones.',        'https://www.harrywinston.com/en-ae',         66, 72,  0.2,1100.0, 140.0,   7.6, '2F – Jewellery Row',  0, 3],
  [67, 'Piaget',              'Watches & Jewels','watches',      'Ultra-thin watchmaking mastery — Piaget\'s Altiplano at 2mm is the conversation starter of every Dubai boardroom.', 'https://www.piaget.com/en-ae/',              67, 74,  0.2, 680.0, 130.0,   6.8, '2F – Watch Gallery', 0, 3],
  [68, 'Jaeger-LeCoultre',    'Watches',         'watches',      'Manufacture Royale — JLC Dubai Mall maintains a private suite for Reverso personalisation appointments.',            'https://www.jaeger-lecoultre.com/en-ae/',    68, 76,  0.2, 620.0, 110.0,   7.1, '2F – Watch Gallery', 0, 3],
  [69, 'IWC Schaffhausen',    'Watches',         'watches',      'Engineering poetry — IWC Big Pilot at Dubai Mall ships in custom carbon cases available nowhere else in the region.','https://www.iwc.com/en-ae/',               69, 75,  0.2, 580.0, 105.0,   7.8, '2F – Watch Gallery', 0, 3],
  [70, 'Graff',               'Jewellery',       'jewellery',    'Exceptional diamonds, exceptionally displayed — Graff Dubai Mall sells more D-colour stones per year than anywhere.','https://www.graff.com/en-ae/',             70, 80,  0.2,1400.0, 100.0,   6.2, '2F – Jewellery Row',  0, 3],
  [71, 'Brunello Cucinelli',  'Luxury Fashion',  'luxury',       'The king of cashmere — Brunello\'s Dubai boutique is the Middle East\'s most requested appointment-only retailer.','https://www.brunellocucinelli.com/en/',     71, 78,  0.2, 590.0, 140.0,   8.4, '2F – Fashion Ave',   0, 3],
  [72, 'Loro Piana',          'Luxury Fashion',  'luxury',       'Vicuña and baby cashmere — Loro Piana Dubai Mall moves the world\'s most expensive fabric by the metre, daily.',    'https://www.loropiana.com/en/eshop/ae',     72, 79,  0.1, 640.0, 120.0,   7.9, '2F – Fashion Ave',   0, 3],
  [73, 'Zegna',               'Luxury Fashion',  'luxury',       'Oasi Cashmere for the discerning gentleman — Zegna\'s bespoke suits take 6 weeks and start at AED 28,000.',        'https://www.zegna.ae/',                      73, 82,  0.1, 520.0, 115.0,   7.2, '2F – Fashion Ave',   0, 3],
  [74, 'Berluti',             'Luxury Shoes',    'luxury',       'The finest shoes in the world, made in Ferrara — Berluti Dubai\'s patina service takes 4 hours and costs AED 3,500.','https://www.berluti.com/en-ae/',          74, 84,  0.1, 480.0, 100.0,   6.5, '2F – Fashion Ave',   0, 3],
  [75, 'Brioni',              'Luxury Fashion',  'luxury',       'The tuxedo of James Bond — Brioni Dubai\'s master tailor Vincenzo has dressed 3 sitting heads of state.',           'https://www.brioni.com/en/',                 75, 86,  0.1, 460.0,  95.0,   5.8, '2F – Fashion Ave',   0, 3],
  [76, 'Stella McCartney',    'Luxury Fashion',  'luxury',       'Luxury without leather or fur — Stella\'s Dubai boutique is the MENA flagship for conscious high fashion.',          'https://www.stellamccartney.com/ae/',        76, 77,  0.1, 380.0, 165.0,  14.8, '2F – Fashion Ave',   0, 3],
  [77, 'De Beers',            'Jewellery',       'jewellery',    'A diamond is forever — De Beers Dubai Mall sources directly from Botswana\'s mines. 0 conflict. 100% traceability.','https://www.debeers.ae/',                  77, 85,  0.1,1200.0, 190.0,   9.1, '2F – Jewellery Row',  0, 3],
  [78, 'Dubai Aquarium',      'Entertainment',   'entertainment','2.5 million litres of ocean — 33,000 aquatic animals including 400 sharks visible through the world\'s largest acrylic panel.','https://www.thedubaiaquarium.com/', 78, 61,  0.1, 180.0, 120.0,  10.3, 'GF – Central Atrium',0, 3],
  [79, 'Dubai Ice Rink',      'Entertainment',   'entertainment','Olympic-size ice rink inside a mall — 2,000 skaters daily. Figure skating shows every Friday at 8pm.',              'https://www.dubaiicerink.com/',              79, 63,  0.1, 140.0,  55.0,   8.7, 'GF – Ice Rink Zone', 0, 3],
  [80, 'VR Park',             'Entertainment',   'entertainment','The Middle East\'s largest virtual reality theme park — 30 VR experiences across 80,000 sq ft of digital immersion.','https://www.vrparkdubai.com/',            80, 64,  0.1, 120.0,  85.0,  22.4, 'B1 – VR Zone',        0, 3],
  [81, 'KidZania',            'Entertainment',   'entertainment','A child-sized city where kids live real careers — KidZania Dubai has 80+ role-play activities across 80,000 sq ft.','https://dubai.kidzania.com/',              81, 69,  0.1, 100.0,  75.0,  12.1, 'B1 – Family Zone',    0, 3],
  [82, 'Reel Cinemas',        'Entertainment',   'entertainment','22 screens including Dubai\'s only IMAX with Laser — Reel Cinemas screens 300 films per week in 5 languages.',      'https://reelcinemas.ae/',                    82, 71,  0.1, 195.0,  90.0,   9.4, '3F – Cinema Level',  0, 3],
  [83, 'New Balance',         'Sports',          'sports',       'The grey ghost — NB Dubai Mall features an exclusive run-club track analysis and the full 990 archive series.',      'https://www.newbalance.ae/',                 83, 73,  0.1, 175.0, 120.0,  18.3, '1F – Sports Zone',   0, 3],
  [84, 'Puma',                'Sports',          'sports',       'Cat DNA runs deep — Puma Dubai Mall stocks the full Nitro+ running franchise and exclusive Arab-heritage colourways.','https://ae.puma.com/',                    84, 81,  0.1, 160.0, 110.0,  14.6, '1F – Sports Zone',   0, 3],
  [85, 'Under Armour',        'Sports',          'sports',       'Performance science in retail form — UA Dubai Mall is the brand\'s #1 Middle East store by athletic apparel volume.','https://www.underarmour.ae/',             85, 83,  0.1, 145.0, 105.0,  11.8, '1F – Sports Zone',   0, 3],
  [86, 'Skechers',            'Shoes',           'shoes',        'Comfort engineered — Skechers Dubai Mall moves 3,000 pairs of GOwalk per month. The region\'s top walking shoe.',  'https://www.skechers.ae/',                   86, 87,  0.1, 155.0, 100.0,  13.5, '1F – Shoes',          0, 3],
  [87, 'Charles & Keith',     'Shoes',           'shoes',        'Singapore\'s luxury-affordable shoe empire — Charles & Keith Dubai Mall leads by-the-season trend forecasting.',    'https://www.charleskeith.ae/',               87, 88,  0.1, 135.0, 120.0,  16.2, '1F – Shoes',          0, 3],
  [88, 'Aldo',                'Shoes',           'shoes',        'Montreal\'s fashion footwear house — Aldo Dubai Mall is the brand\'s top global store by fashion-forward velocity.','https://www.aldoshoes.com/ae/',            88, 89,  0.1, 125.0, 115.0,  12.7, '1F – Shoes',          0, 3],
  [89, 'Steve Madden',        'Shoes',           'shoes',        'Brooklyn\'s rock \'n roll cobbler — Steve Madden Dubai Mall exclusively carries the ME-region MadGirl collab line.', 'https://stevemadden.ae/',                  89, 90,  0.1, 118.0, 108.0,  11.4, '1F – Shoes',          0, 3],
  [90, 'Nine West',           'Shoes',           'shoes',        'American confidence on heels — Nine West Dubai Mall\'s bridal collection books a 3-month fitting schedule.',        'https://www.ninewest.ae/',                   90, 91,  0.1, 105.0,  90.0,   8.9, '1F – Shoes',          0, 3],
  [91, 'Ecco',                'Shoes',           'shoes',        'Danish ergonomic excellence — Ecco Dubai Mall custom-fits footbeds for every purchase. 45-minute consultations.',   'https://www.ecco.com/ae/',                   91, 92,  0.1, 115.0,  85.0,   9.2, '1F – Shoes',          0, 3],
  [92, 'Reebok',              'Sports',          'sports',       'The Pump returns — Reebok\'s Dubai Mall Classic Collection is piloted here before any other global market.',         'https://www.reebok.ae/',                     92, 93,  0.1, 140.0,  95.0,  12.1, '1F – Sports Zone',   0, 3],
  [93, 'American Eagle',      'Fashion',         'fashion',      'Denim democracy for Dubai\'s campus crowd — AEO Dubai Mall sells 8,000+ pairs of jeans per month peak season.',     'https://www.ae.com/ae/',                     93, 94,  0.1, 120.0, 100.0,  10.8, '1F – Fashion Ave',   0, 3],
  [94, 'Kiton',               'Luxury Fashion',  'luxury',       'Naples\' most exclusive tailor — Kiton Dubai does 4 fittings minimum. A suit takes 25 hours of hand-stitching.',   'https://www.kiton.it/en/',                   94, 97,  0.1, 580.0,  70.0,   6.4, '2F – Fashion Ave',   0, 3],
  [95, 'A. Lange & Söhne',    'Watches',         'watches',      'Dresden watchmaking perfection — only 5,000 watches per year globally. Dubai Mall receives an allocated 38.',       'https://www.alange-soehne.com/en/',          95, 98,  0.1, 920.0,  60.0,   6.8, '2F – Watch Gallery', 0, 3],
  [96, 'Canali',              'Luxury Fashion',  'luxury',       'Milan\'s power suit architect — Canali Dubai Mall kits out C-suite executives with 48-hour made-to-measure.',       'https://www.canali.com/en-ae/',              96, 96,  0.1, 390.0,  88.0,   7.1, '2F – Fashion Ave',   0, 3],
  [97, 'Graff Diamonds',      'Jewellery',       'jewellery',    'The rarest diamonds on Earth, here — Graff Dubai holds the Gulf\'s only pink diamond exceeding 10 carats.',         'https://www.graff.com/en-ae/',               97, 99,  0.1,1600.0,  80.0,   5.9, '2F – Jewellery Row',  0, 3],
  [98, 'De Grisogono',        'Jewellery',       'jewellery',    'Geneva\'s most daring jewel house — De Grisogono black diamonds are the signature of Dubai\'s boldest collectors.',  'https://www.degrisogono.com/',              98,100,  0.1, 480.0,  65.0,   6.2, '2F – Jewellery Row',  0, 3],
  [99, 'Piaget Polo Club',    'Watches',         'watches',      'The sports watch reimagined — Piaget Polo at Dubai Mall includes a live polo simulation and watch-sport pairing.',   'https://www.piaget.com/en-ae/',              99, 95,  0.1, 550.0,  70.0,   6.5, '2F – Watch Gallery', 0, 3],
  [100,'Dubai Dino',          'Attraction',      'entertainment','Sue the T-Rex — a 155-million-year-old Diplodocus presides over Dubai Mall\'s atrium. Tallest dinosaur fossil displayed commercially.','https://www.thedubaimall.com/',100, 51,  0.1, 40.0, 180.0,  24.1, 'GF – Central Atrium',0, 3],
];

async function seed() {
  const pool = mysql.createPool({
    host: env.DB_HOST || '127.0.0.1',
    port: parseInt(env.DB_PORT || '3306'),
    user: env.DB_USER || 'root',
    password: env.DB_PASSWORD || '',
    database: env.DB_NAME || 'dubai_mall',
  });

  // Clear existing
  await pool.execute('DELETE FROM retail_shops');
  await pool.execute('ALTER TABLE retail_shops AUTO_INCREMENT = 1');

  let inserted = 0;
  for (const b of BRANDS) {
    const [rank, name, category, cat_slug, desc, url,
           off_rank, on_rank, footfall, off_rev, on_rev, yoy, floor, featured, tier] = b;
    await pool.execute(
      `INSERT INTO retail_shops
         (fortune_rank, name, category, category_slug, description, website_url,
          offline_rank, online_rank, annual_footfall_m, offline_revenue_m, online_revenue_m,
          yoy_growth, floor_level, is_featured, tier, needs_catered)
       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
      [rank, name, category, cat_slug, desc, url,
       off_rank, on_rank, footfall, off_rev, on_rev, yoy, floor, featured, tier,
       `${category} · Fortune Rank #${rank}`]
    );
    inserted++;
    process.stdout.write(`\r  Inserted ${inserted}/100 — #${rank} ${name}`);
  }
  console.log('\n✅ 100 retailers seeded with Fortune rankings');
  await pool.end();
}

seed().catch(console.error);
